name: Release
on:
  workflow_dispatch:

jobs:
  build:
    name: Manual release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Setup node.js v16.x 
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: https://registry.npmjs.org/

      - run: npm build
      - run: npm run publish:public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
